//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crp10
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class АВТОПРОКАТEntities : DbContext
    {
        private static АВТОПРОКАТEntities _context;
        public АВТОПРОКАТEntities()
            : base("name=АВТОПРОКАТEntities")
        {
        }
        public static АВТОПРОКАТEntities GetContext()
        {
            if (_context == null)
                _context = new АВТОПРОКАТEntities();
            return _context;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<АВТОМОБИЛИ> АВТОМОБИЛИ { get; set; }
        public virtual DbSet<АРЕНДА> АРЕНДА { get; set; }
        public virtual DbSet<ЗАЯВКИ> ЗАЯВКИ { get; set; }
        public virtual DbSet<КЛИЕНТЫ> КЛИЕНТЫ { get; set; }
        public virtual DbSet<ПОЛЬЗОВАТЕЛИ> ПОЛЬЗОВАТЕЛИ { get; set; }
        public virtual DbSet<РОЛЬ> РОЛЬ { get; set; }
        public virtual DbSet<СОТРУДНИКИ> СОТРУДНИКИ { get; set; }
        public virtual DbSet<ТАРИФЫ> ТАРИФЫ { get; set; }
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<ZAYAVKI> ZAYAVKI { get; set; }
    }
}
