//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crp10
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAYAVKI
    {
        public int ID { get; set; }
        public int ID_avto { get; set; }
        public int ID_user { get; set; }
        public System.DateTime Дата_Начала_Аренды { get; set; }
        public System.DateTime Дата_Конца_Аренды { get; set; }
        public System.TimeSpan Время_Вывоза { get; set; }
        public System.TimeSpan Время_Возврата { get; set; }
        public string Получение_авто { get; set; }
        public string Сдача_авто { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Телефон { get; set; }
        public string Email { get; set; }
        public string Статус { get; set; }
    }
}
