//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crp10
{
    using System;
    using System.Collections.Generic;
    
    public partial class АВТОМОБИЛИ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public АВТОМОБИЛИ()
        {
            this.АРЕНДА = new HashSet<АРЕНДА>();
            this.ЗАЯВКИ = new HashSet<ЗАЯВКИ>();
            this.ТАРИФЫ = new HashSet<ТАРИФЫ>();
        }
    
        public int ID { get; set; }
        public string Марка { get; set; }
        public string Модель { get; set; }
        public Nullable<short> Год_выпуска { get; set; }
        public string Цвет { get; set; }
        public string Номерной_знак { get; set; }
        public string VIN_код { get; set; }
        public string Серия_номер_СТС { get; set; }
        public Nullable<System.DateTime> Дата_выдачи_СТС { get; set; }
        public string Серия_номер_ПТС { get; set; }
        public Nullable<System.DateTime> Дата_выдачи_ПТС { get; set; }
        public byte[] Фото { get; set; }
        public string Страховка { get; set; }
        public Nullable<System.DateTime> Ремонт { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<АРЕНДА> АРЕНДА { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗАЯВКИ> ЗАЯВКИ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТАРИФЫ> ТАРИФЫ { get; set; }
    }
}
