//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crp10
{
    using System;
    using System.Collections.Generic;
    
    public partial class АРЕНДА
    {
        public int ID { get; set; }
        public Nullable<int> ID_client { get; set; }
        public Nullable<int> ID_user { get; set; }
        public Nullable<int> ID_avto { get; set; }
        public Nullable<System.DateTime> Дата_Начала_Аренды { get; set; }
        public Nullable<System.DateTime> Дата_Конца_Аренды { get; set; }
        public Nullable<int> Цена { get; set; }
        public string ФИО { get; set; }
        public string Статус { get; set; }
    
        public virtual АВТОМОБИЛИ АВТОМОБИЛИ { get; set; }
        public virtual КЛИЕНТЫ КЛИЕНТЫ { get; set; }
        public virtual ПОЛЬЗОВАТЕЛИ ПОЛЬЗОВАТЕЛИ { get; set; }
    }
}
