//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crp10
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗАЯВКИ
    {
        public int ID { get; set; }
        public Nullable<int> ID_avto { get; set; }
        public Nullable<int> ID_user { get; set; }
        public Nullable<System.DateTime> Дата_Начала_Аренды { get; set; }
        public Nullable<System.DateTime> Дата_Конца_Аренды { get; set; }
        public Nullable<System.TimeSpan> Время_Вывоза { get; set; }
        public Nullable<System.TimeSpan> Время_Возврата { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Телефон { get; set; }
        public string Emai { get; set; }
    
        public virtual АВТОМОБИЛИ АВТОМОБИЛИ { get; set; }
        public virtual ПОЛЬЗОВАТЕЛИ ПОЛЬЗОВАТЕЛИ { get; set; }
    }
}
