//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crp10
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТАРИФЫ
    {
        public int ID { get; set; }
        public Nullable<int> ID_avto { get; set; }
        public string Марка_Модель { get; set; }
        public Nullable<int> Цена_1_2_суток { get; set; }
        public Nullable<int> Цена_3_6_суток { get; set; }
        public Nullable<int> Цена_7_15_суток { get; set; }
        public Nullable<int> Цена_16_30_суток { get; set; }
        public Nullable<int> Залог { get; set; }
    
        public virtual АВТОМОБИЛИ АВТОМОБИЛИ { get; set; }
    }
}
